# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='JD',
        ),
        migrations.RemoveField(
            model_name='job',
            name='relative_time',
        ),
    ]
