# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='JD',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='relative_time',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(default=12, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
