# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0003_auto_20170407_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.AddField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
