# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0007_auto_20170407_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.FloatField(default=12, primary_key=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
