# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0008_auto_20170408_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
