# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0011_auto_20170408_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
